{% set name = "gammasimtools" %}
{% set version = "0.13.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gammasimtools-{{ version }}.tar.gz
  sha256: 68f1dcc010a405a414dc22f7562acbb36bb27b29a3af408bcbfd9d5b6c7d11e1

build:
  entry_points:
    - simtools-calculate-trigger-rate = simtools.applications.calculate_trigger_rate:main
    - simtools-convert-all-model-parameters-from-simtel = simtools.applications.convert_all_model_parameters_from_simtel:main
    - simtools-convert-geo-coordinates-of-array-elements = simtools.applications.convert_geo_coordinates_of_array_elements:main
    - simtools-convert-model-parameter-from-simtel = simtools.applications.convert_model_parameter_from_simtel:main
    - simtools-db-add-file-to-db = simtools.applications.db_add_file_to_db:main
    - simtools-db-add-simulation-model-from-repository-to-db = simtools.applications.db_add_simulation_model_from_repository_to_db:main
    - simtools-db-add-value-from-json-to-db = simtools.applications.db_add_value_from_json_to_db:main
    - simtools-db-get-array-layouts-from-db = simtools.applications.db_get_array_layouts_from_db:main
    - simtools-db-get-file-from-db = simtools.applications.db_get_file_from_db:main
    - simtools-db-get-parameter-from-db = simtools.applications.db_get_parameter_from_db:main
    - simtools-db-inspect-databases = simtools.applications.db_inspect_databases:main
    - simtools-derive-mirror-rnda = simtools.applications.derive_mirror_rnda:main
    - simtools-derive-photon-electron-spectrum = simtools.applications.derive_photon_electron_spectrum:main
    - simtools-derive-psf-parameters = simtools.applications.derive_psf_parameters:main
    - simtools-docs-produce-array-element-report = simtools.applications.docs_produce_array_element_report:main
    - simtools-docs-produce-model-parameter-reports = simtools.applications.docs_produce_model_parameter_reports:main
    - simtools-generate-array-config = simtools.applications.generate_array_config:main
    - simtools-generate-corsika-histograms = simtools.applications.generate_corsika_histograms:main
    - simtools-generate-default-metadata = simtools.applications.generate_default_metadata:main
    - simtools-generate-regular-arrays = simtools.applications.generate_regular_arrays:main
    - simtools-generate-simtel-array-histograms = simtools.applications.generate_simtel_array_histograms:main
    - simtools-plot-array-layout = simtools.applications.plot_array_layout:main
    - simtools-plot-tabular-data = simtools.applications.plot_tabular_data:main
    - simtools-production-derive-corsika-limits = simtools.applications.production_derive_corsika_limits:main
    - simtools-production-extract-mc-event-data = simtools.applications.production_extract_mc_event_data:main
    - simtools-production-generate-simulation-config = simtools.applications.production_generate_simulation_config:main
    - simtools-production-scale-events = simtools.applications.production_scale_events:main
    - simtools-run-application = simtools.applications.run_application:main
    - simtools-simulate-light-emission = simtools.applications.simulate_light_emission:main
    - simtools-simulate-prod = simtools.applications.simulate_prod:main
    - simtools-simulate-prod-htcondor-generator = simtools.applications.simulate_prod_htcondor_generator:main
    - simtools-submit-data-from-external = simtools.applications.submit_data_from_external:main
    - simtools-submit-model-parameter-from-external = simtools.applications.submit_model_parameter_from_external:main
    - simtools-validate-camera-efficiency = simtools.applications.validate_camera_efficiency:main
    - simtools-validate-camera-fov = simtools.applications.validate_camera_fov:main
    - simtools-validate-cumulative-psf = simtools.applications.validate_cumulative_psf:main
    - simtools-validate-file-using-schema = simtools.applications.validate_file_using_schema:main
    - simtools-validate-optics = simtools.applications.validate_optics:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - boost-histogram
    - ctao-dpps-cosmic-ray-spectra
    - ctapipe-base
    - eventio
    - h5py
    - jsonschema
    - matplotlib-base
    - numpy
    - particle
    - pymongo
    - pyproj
    - python-dotenv
    - pyyaml
    - pytest
    - scipy
    - toml

test:
  imports:
    - simtools
  commands:
    - pip check
    - simtools-calculate-trigger-rate --help
    - simtools-convert-all-model-parameters-from-simtel --help
    - simtools-convert-geo-coordinates-of-array-elements --help
    - simtools-convert-model-parameter-from-simtel --help
    - simtools-db-add-file-to-db --help
    - simtools-db-add-simulation-model-from-repository-to-db --help
    - simtools-db-add-value-from-json-to-db --help
    - simtools-db-get-array-layouts-from-db --help
    - simtools-db-get-file-from-db --help
    - simtools-db-get-parameter-from-db --help
    - simtools-db-inspect-databases --help
    - simtools-derive-mirror-rnda --help
    - simtools-derive-photon-electron-spectrum --help
    - simtools-derive-psf-parameters --help
    - simtools-docs-produce-array-element-report --help
    - simtools-docs-produce-model-parameter-reports --help
    - simtools-generate-array-config --help
    - simtools-generate-corsika-histograms --help
    - simtools-generate-default-metadata --help
    - simtools-generate-regular-arrays --help
    - simtools-generate-simtel-array-histograms --help
    - simtools-plot-array-layout --help
    - simtools-plot-tabular-data --help
    - simtools-production-derive-corsika-limits --help
    - simtools-production-generate-simulation-config --help
    - simtools-production-extract-mc-event-data --help
    - simtools-production-scale-events -help
    - simtools-run-application --help
    - simtools-simulate-light-emission --help
    - simtools-simulate-prod --help
    - simtools-simulate-prod-htcondor-generator --help
    - simtools-submit-data-from-external --help
    - simtools-submit-model-parameter-from-external --help
    - simtools-validate-camera-efficiency --help
    - simtools-validate-camera-fov --help
    - simtools-validate-cumulative-psf --help
    - simtools-validate-file-using-schema --help
    - simtools-validate-optics --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gammasim/simtools
  summary: Tools for the Simulation System of the CTA Observatory
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Simulation tools and applications for the Cherenkov Telescope Array (CTAO).

extra:
  recipe-maintainers:
    - orelgueta
    - GernotMaier
    - maxnoe
