{% set name = "gammasimtools" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gammasimtools-{{ version }}.tar.gz
  sha256: be70b29620ecc186a52c14540e612e92cafa94bfabe7287d0f355bebf106b968

build:
  entry_points:
    - simtools-add-file-to-db = simtools.applications.add_file_to_db:main
    - simtools-compare-cumulative-psf = simtools.applications.compare_cumulative_psf:main
    - simtools-derive-mirror-rnda = simtools.applications.derive_mirror_rnda:main
    - simtools-generate-corsika-histograms = simtools.applications.generate_corsika_histograms:main
    - simtools-generate-default-metadata = simtools.applications.generate_default_metadata:main
    - simtools-generate-simtel-array-histograms = simtools.applications.generate_simtel_array_histograms:main
    - simtools-get-file-from-db = simtools.applications.get_file_from_db:main
    - simtools-get-parameter = simtools.applications.get_parameter:main
    - simtools-make-regular-arrays = simtools.applications.make_regular_arrays:main
    - simtools-plot-array-layout = simtools.applications.plot_array_layout:main
    - simtools-plot-simtel-histograms = simtools.applications.plot_simtel_histograms:main
    - simtools-print-array-elements = simtools.applications.print_array_elements:main
    - simtools-produce-array-config = simtools.applications.produce_array_config:main
    - simtools-production = simtools.applications.production:main
    - simtools-sim-showers-for-trigger-rates = simtools.applications.sim_showers_for_trigger_rates:main
    - simtools-simulate-prod = simtools.applications.simulate_prod:main
    - simtools-submit-data-from-external = simtools.applications.submit_data_from_external:main
    - simtools-tune-psf = simtools.applications.tune_psf:main
    - simtools-validate-camera-efficiency = simtools.applications.validate_camera_efficiency:main
    - simtools-validate-camera-fov = simtools.applications.validate_camera_fov:main
    - simtools-validate-file-using-schema = simtools.applications.validate_file_using_schema:main
    - simtools-validate-optics = simtools.applications.validate_optics:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=65
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - astropy
    - boost-histogram
    - ctapipe
    - eventio
    - jsonschema
    - matplotlib-base
    - numpy
    - pymongo
    - pyproj
    - python-dotenv
    - pyyaml
    - scipy
    - toml

test:
  imports:
    - simtools
  commands:
    - pip check
    - simtools-add-file-to-db --help
    - simtools-compare-cumulative-psf --help
    - simtools-derive-mirror-rnda --help
    - simtools-generate-corsika-histograms --help
    - simtools-generate-default-metadata --help
    - simtools-generate-simtel-array-histograms --help
    - simtools-get-file-from-db --help
    - simtools-get-parameter --help
    - simtools-make-regular-arrays --help
    - simtools-plot-array-layout --help
    - simtools-print-array-elements --help
    - simtools-produce-array-config --help
    - simtools-production --help
    - simtools-sim-showers-for-trigger-rates --help
    - simtools-simulate-prod --help
    - simtools-submit-data-from-external --help
    - simtools-tune-psf --help
    - simtools-validate-camera-efficiency --help
    - simtools-validate-camera-fov --help
    - simtools-validate-file-using-schema --help
    - simtools-validate-optics --help
  requires:
    - pip

about:
  home: https://github.com/gammasim/simtools
  summary: Tools for the Simulation System of the CTA Observatory
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - GernotMaier
    - maxnoe
